## Actividad Módulo 8

In [9]:
import numpy as np

### Ejercicio 1

In [10]:
# Escribe un programa que mediante indexación sea capaz de invertir un arreglo
ejercicio1 = np.arange(12,21)
# Voltaear el arreglo y mostrarlo
ejercicio1[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12])

### Ejercicio 2
Escribe un programa para convertir valores de grados Farenheit a grados centígrados

In [11]:
ejercicio2_entrada = np.array([0, 12, 45.21, 34, 99.91, 32])
# Hacer conversión utilizando operaciones con escalares
ejercicio2_salida = (ejercicio2_entrada - 32) / 1.8
# Mostrar arreglo
ejercicio2_salida

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778,   0.        ])

### Ejercicio 3
Escribe un programa con NumPy para encontrar la unión de dos arreglos. La unión debe devolver un arreglo ordenado de valores que están en cualquiera de los dos arreglos de entrada sin repetir valores

In [12]:
ej3_arreglo1 = np.array([0,10,20])
ej3_arreglo2 = np.array([20,10,30])

# Unir arreglos
ej3_arreglofinal = np.concatenate((ej3_arreglo1,ej3_arreglo2))
# Eliminar elementos duplicados del arreglo final
ej3_arreglofinal = np.unique(ej3_arreglofinal)
# Mostrar arreglo
ej3_arreglofinal

array([ 0, 10, 20, 30])